# Site Meta
title:            Codemons
tagline:          Building Great Apps For A Better World
description:      This site is centered around my blog, but contains lots of other content as well. You can use the links at the top, or else jump right to the various sections.


domain:           codemons.com
type:             website
logo:             /logo.png

contact:  contact@codemons.com

# Author details
author:
  name:           'Shivaji Varma'
  location:        'Bangalore, India'
  gpage:          +ShivajivarmaDotCom
  email:          contact@shivajivarma.com
  avatar:         /profile.jpg
  fbid:           100002868559363
  gplusid:        108142170241252227550
  github:         shivajivarma
  soundcloud:     shivajivarma
  linkedin:       shivajivarma
  twitter:        shivaji_varma
  youtube:        enchantingstrings

team:
  shivaji: Shivaji Varma
  venky: Venkatesh

#Assets paths
css: /assets/css
js: /assets/js
img: /assets/img
font: /assets/font

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: codemons

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-42422649-2

baseurl:          ''

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://codemons.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:categories/:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: compressed #expanded # You might prefer to minify using :compressed
  sass_dir: assets/css/_scss
# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
